### PR TITLE
Compliance sites

### PR DESCRIPTION
**Pull request by mjp**
Compliance microsites for HIPAA and GDPR:

https://www.aptible-staging.com/hipaa/
https://www.aptible-staging.com/gdpr/

### CODE REVIEW

**Comment by krallin** [comment]
@mjp a few pieces of feedback:

- The search appears to capture the sidebar for each page, so if you search for e.g. "baa", then every page matches because we have "baa" in the sidebar. It also means the preview of the text is a little useless since it's always `HIPAA Compliance Guide  •  Kit Contact Login Login Signup Get Started HIPAA Compliance Guide HIPAA Overview & Regulations HIPAA Compliance Guide What is HIPAA? What is a HIPAA BAA? Regulations General Administrative Requirements Subpart A General Provisions § 160.101 Statutory basis and purpose § 160.102 Applicability § 160.103`
- Should we redirect the old https://www.aptible.com/resources/what-is-a-hipaa-baa/# ?

**Comment by krallin** [comment]
Ah, it looks like you do have the redirect setup (but it does not seem to redirect on aptible-staging, so I'm not sure why). How did you deploy to aptible-staging? I'm guessing that might be simply the reason why here

**Comment by mjp** [comment]
@krallin I deployed it to staging with: `bundle exec rake deploy:staging`

**Comment by sandersonet** [comment]
To @krallin's point, it looks like the entirety of each page is indexed.  Looks like this could be fixed with some simple whitelist/blacklist tags made available by swiftype?  https://swiftype.com/documentation/site-search/crawler-features#content_inclusion_exclusion

**Comment by sandersonet** [comment]
I might consider flipping the default visibility of `.compliance__expandable__content` to `display:block` rather than `display:none`.  As it stands right now, with JS disabled, the sidebar will be hidden. I'm not sure if there are SEO implications for this, but I'm pretty sure Google will ignore links that are `display:none` in an effort to combat hidden link farms.

**Pull request merged**
