### PR TITLE
Added coffeescript, vendor js (animate[npm], fullpage[bower]), technology template and partial 

### PR DESCRIPTION
**Pull request by moeamaya**

### CODE REVIEW

**Comment by moeamaya** [comment]
One concern is with some straight .js files I wrote. I put them in the /vendor file which I realize now is bower dependent.

I will rewrite the files in coffeescript and put them in the src folder.

**Comment by chasballew** [comment]
@skylar - code review?

**Comment by skylar** [comment]
@chasballew I don't think I know this project?

**Comment by chasballew** [comment]
Sorry, wrong @skylar. My bad.

**Comment by sandersonet** [comment]
@moeamaya - Really sharp stuff here Moe, thanks for your hard work.   Merge at will!

**Pull request merged**
