### PR TITLE
fix toc for baa resource

### PR DESCRIPTION
**Pull request by henryhund**
Removed trailing `-` from anchors.

### CODE REVIEW

**Comment by fancyremarker** [comment]
These aren't quite right; I'll push up a commit with the correct anchors and merge.

**Comment by gib** [comment]
@henryhund - I right-click-inspect the titles and copy / past the ID value when creating these TOC links. It isn't always clear how these are generated... contractions just lose the apostrophe I guess:

**Comment by henryhund** [comment]
@fancyremarker what was the issue with what I did?

**Comment by gib** [comment]
@henryhund - I took this off @fancyremarker's plate. How did you come up with the links you used? You have to look at the generated HTML to find the ID attribute of the header you're trying to link to:

toc-links

**Pull request merged**
