### PR TITLE
Integrated pricing calculator

### PR DESCRIPTION
**Pull request by carlfairclough**
It's ll contained inside one partial called with `{{> pricing_calc}}`
Two external files are hosted by google (jquery ui js & css)

### CODE REVIEW

**Comment by sandersonet** [comment]
@carlfairclough Thanks for the PR!  Before we can do a more detailed review, I think there are several general style issues to address.

The variable names used throughout are cryptic and difficult to follow.  Optimize these for the reader as much as possible, `aReallyLongDescriptiveVariableIsAlwaysBetter`.

The overall flow is difficult to follow.  Try and lead your files with the most important methods on top, and then trail downwards to the more menial.  Also, the functions you do have defined are way to large.  Try to keep functions as small and specific as possible.  Function calls are a great way to annotate your code without using comments.  There are also many opportunities to reduce duplicated code by just using functions instead.

You could also convert some of the methods into jQuery plugins that can be called on DOM elements directly, rather than passing around the elements into function calls.  

Using `$('...')` repeatedly is hurting readability(and performance).  Querying the DOM for the same elements is unnecessary.   Store all of the elements you need to use in variables.  This also goes for getting values like `.attr('userval')`--store these in variables.

Use more whitespace.  I would also consider switching back to vanilla JS, when I last saw your code, I thought it was more readable.

Don't use `.css()` to modify the appearance of elements.  Instead, create a meaningful CSS class and just add/remove it to elements where you need to.  This is easier to read and maintain.

Not sure I want to load the entirety of jquery-UI for just the sliders. Can you add a bower dependency and just load the slider plugin specifically.  Same with CSS

Use the bootstrap grid system rather than rolling your own.

**Comment by sandersonet** [comment]
Also, there are many cases where you are using backticks to escape back to vanilla JS. That should never be necessary and should be avoided.

**Comment by carlfairclough** [comment]
I think that a lot of these issues stem from moving from JS to coffeescript, especially the backticks and whitespace

`.css()` vs classes
I'm modifying using .css/.animate to ensure that transitions work, for example:
`.css()` makes an element visible, `.outerHeight()` is found, then `.css()` again hides the element.
The parent container height is animated using the `.outerHeight()` var, the element is again made visible, and classes are added at the end. Finally, all height css changes are cleared so that the height is not fixed. It's archaic, but works.

Everything else is fair.

**Comment by sandersonet** [comment]
@carlfairclough Got it, that makes sense.  Also, I forgot to say that the design and UX is really fantastic, and overall, this is going to be a really helpful feature for us.  Thanks!

**Comment by carlfairclough** [comment]
@sandersonet Okay, I've updated it based on your feedback. There is still a big function in there, but it's functional and all sandboxed and I'm conscious of spending much longer on this (diminishing returns). That being said, if there's anything that stands out to you then let me know.

Side note: apologies for the little string of commits

**Comment by fancyremarker** [comment]
Closing this for now, but thanks @carlfairclough for the great interface! We'll re-open another PR soon, including these changes.

**Pull request closed without merging**
