### PR TITLE
Add compliance cycle to compliance page

### PR DESCRIPTION
**Pull request by sandersonet**
Hey @chasballew , this is a quick implementation of an animated compliance cycle.  You can see it in action here:
https://www.aptible-staging.com/compliance/

This obviously needs some copy work.  Please feel free to comment with your feedback or patch the PR with copy updates directly.  

The copy is primarily in the aptible-pages PR: https://github.com/aptible/aptible-pages/pull/95

### CODE REVIEW

**Comment by chasballew** [comment]
Nice, looks great. I'll loop back to this tomorrow.

**Comment by sandersonet** [comment]
@chasballew  Updated design to tie security program and compliance cycle:

screenshot 2015-03-04 11 37 21

**Comment by fancyremarker** [comment]
@chas and @sandersonet: Is this staying open for further review, or should we merge or close?

**Comment by sandersonet** [comment]
Closing for now.

**Pull request closed without merging**
