### PR TITLE
Nav Update

### PR DESCRIPTION
**Pull request by gib**
new-nav

new-nav-mobile

This will work, but I'm not happy with the mobile because it reduces the added content to a list of links that is too long to take in. Peter did a full screen design that would drill down each section to sub lists, but the design only thought through one type of sub-nav... we have three different types. I'd like to pick this back up soon.

### CODE REVIEW

**Comment by henryhund** [comment]
@gib On my laptop screen, the alignment of the product icons is off, even when the window is full width

screen shot 2017-10-12 at 11 05 52 am

**Comment by henryhund** [comment]
The text for the products dropdown should read:

Enclave - Container orchestration platform with built-in security and compliance
Gridiron - Security and compliance management for software development teams

**Comment by gib** [comment]
@henryhund -- looks like the font isn't loading for you and causing the text to wrap.

**Comment by henryhund** [comment]
@gib nav doesn't wrap strangely anymore!

screen shot 2017-10-17 at 9 44 06 am

**Pull request merged**
